import AppHeader from '@/components/layout/app-header';
import { AppSidebar } from '@/components/layout/app-sidebar';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { ElementStoreProvider } from '@/hooks/use-element-store';
import React from 'react';
import '../styles/globals.css';

export const metadata = {
  title: 'Unsur - Table Periodic of Element',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mx-auto bg-background dark">
        <SidebarProvider>
          <ElementStoreProvider>
            <AppSidebar />

            <SidebarInset>
              <AppHeader />
              {children}
            </SidebarInset>
          </ElementStoreProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
